// if the database is empty on server start, create some sample data.
Meteor.startup(function () {
    if (Anatomy.find().count() === 0) {
        var data = [
              {name: "abdominalArteries"},
              {name: "abdominalArteriesAndVeins"},
              {name: "abdominalOverview"},
              {name: "arteresAndVeinsOfUterus"},
              {name: "arteriesAndVeinsOfNeck"},
              {name: "arteriesAndVeinsOfUpperExtremities"},
              {name: "arteriesAndViensOfLowerExtremities"},
              {name: "arteriesOfLowerExtremities1"},
              {name: "arteriesOfLowerExtremities2"},
              {name: "arteriesOfTheColon"},
              {name: "arteriesOfTheHead"},
              {name: "arteriesOfTheStomach"},
              {name: "arteriesOfUpperExtremities2"},
              {name: "baseOfSkull"},
              {name: "bloodcells"},
              {name: "boneGrowth"},
              {name: "brain1"},
              {name: "brain2"},
              {name: "brain3"},
              {name: "brain4"},
              {name: "brain5"},
              {name: "bridgeOfNose"},
              {name: "cardiac-system"},
              {name: "cerabelloCortex1"},
              {name: "chestArteries"},
              {name: "circleOfWillis"},
              {name: "dental"},
              {name: "digestiveGlands"},
              {name: "digestiveSystemArteriesAndVeins"},
              {name: "digestiveTrack"},
              {name: "ear1"},
              {name: "ear2"},
              {name: "ear3"},
              {name: "ear4"},
              {name: "earCanalBones"},
              {name: "extremetesCartilidge"},
              {name: "eye1"},
              {name: "eye2"},
              {name: "eye3"},
              {name: "facialOpticArteriesAndVeins"},
              {name: "feet"},
              {name: "femaleSexualOrgans"},
              {name: "femoralStressAngles"},
              {name: "femoralVeinsAndArteries"},
              {name: "foramenMagnum"},
              {name: "fornix"},
              {name: "gastricEmbryology"},
              {name: "generalGlandsOfExtremities"},
              {name: "hands"},
              {name: "headNeckMuscles"},
              {name: "heart1"},
              {name: "heart2"},
              {name: "hipJoint"},
              {name: "hypothalmus"},
              {name: "kidneys"},
              {name: "knee"},
              {name: "larynx1"},
              {name: "larynx2"},
              {name: "lateralFeet"},
              {name: "legMuscles"},
              {name: "liver"},
              {name: "lowerExtremityBones"},
              {name: "lungs1"},
              {name: "lungs2"},
              {name: "lungs3"},
              {name: "lymphNodesOfTheHead"},
              {name: "maleSexualOrgans"},
              {name: "mandible"},
              {name: "mandibleLigiments"},
              {name: "maxillaryFaceBones"},
              {name: "medullaOblongata1"},
              {name: "medullaOblongata2"},
              {name: "musclesOfLowerLeg"},
              {name: "musclesOfTheHand"},
              {name: "nasalFacialNerves"},
              {name: "neckArteries"},
              {name: "neckLigiments"},
              {name: "neckVeinsAndArteries"},
              {name: "nerveDiagram1"},
              {name: "nerveDiagram2"},
              {name: "nerveOverview"},
              {name: "nervesOfTheFaceAndMandible"},
              {name: "nervesOfTheGut"},
              {name: "nervesOfTheLowerExtremities"},
              {name: "nervesOfTheLowerExtremities2"},
              {name: "nervesOfTheNeck2"},
              {name: "nervesOfThePelvis"},
              {name: "nervesOfTheShoulder"},
              {name: "nervesOfTheTorso"},
              {name: "nervesOfTheUpperExtremities"},
              {name: "nose"},
              {name: "noseBones"},
              {name: "opticRecess"},
              {name: "opticSystem"},
              {name: "orbits"},
              {name: "parotidGlandAndDucts"},
              {name: "pelvicBone"},
              {name: "pelvicGlands"},
              {name: "pharynx"},
              {name: "prostate"},
              {name: "rectum"},
              {name: "rib"},
              {name: "ribcage"},
              {name: "ribLigiments"},
              {name: "ribMuscles"},
              {name: "ribsLungs"},
              {name: "scapulaeClavical"},
              {name: "sexMuscles"},
              {name: "sexualDevelopment"},
              {name: "sexualDevelopment2"},
              {name: "skin"},
              {name: "skull"},
              {name: "skullPlates"},
              {name: "spinalNerves1"},
              {name: "spinalNerves2"},
              {name: "sternum"},
              {name: "stomachAndSmallIntestines"},
              {name: "tailbone"},
              {name: "testes"},
              {name: "thyroid"},
              {name: "tongue2"},
              {name: "torsoMuscles"},
              {name: "torsoOverview"},
              {name: "tosoGlands"},
              {name: "tounge"},
              {name: "tympanicDevelopment"},
              {name: "upperArmMuscles"},
              {name: "upperExtremityBones"},
              {name: "veinsOfHead"},
              {name: "veinsOfTheNeck"},
              {name: "vertebrae"},
              {name: "vertebralVeins"},
              {name: "vocalCords"},
        ];

        for (var i = 0; i < data.length; i++) {
            Anatomy.insert({
              name:   data[i].name,
              image: '/packages/clinical_grays-anatomy/grays.anatomy.tiles/' + data[i].name + '.png',
              thumbnail: '/packages/clinical_grays-anatomy/grays.anatomy.thumbnails/' + data[i].name + '.png'
            });
        }
    }
});
